fixes:
  - "io/ballerina/stdlib/ftp/compiler/::./compiler-plugin/src/main/java/io/ballerina/stdlib/ftp/plugin/"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
ignore:
  - "test-utils/"
  - "examples"
  - "load-tests"
  - "compiler-plugin-tests"
