name: PR build

on: pull_request

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build --scan
      - name: Archive Code Coverage JSON
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage JSON
          path: ftp-ballerina/target/report/test_results.json
          if-no-files-found: ignore
      - name: Generate Codecov Report
        if: github.event_name == 'pull_request'
        id: uploadReport
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          fail_ci_if_error: true
      - name: Wait after upload failure
        if: steps.uploadReport.outcome == 'failure'
        run: |
          sleep 300s
      - name: Generate Codecov Report V2
        if: steps.uploadReport.outcome == 'failure'
        uses: codecov/codecov-action@v2

  windows-build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat build --scan
